.TH "bCognize.cpp" 3 "21 Apr 2009" "Version 0.1" "BrainCognize" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bCognize.cpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.RI "\fIThe main routine starting up the whole application. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"
.PP
The main routine starting up the whole application. 
.PP
Definition at line 16 of file bCognize.cpp.
.PP
References BMainWindow::setupGUI().
.SH "Author"
.PP 
Generated automatically by Doxygen for BrainCognize from the source code.
