.TH "BMainWindow.h" 3 "21 Apr 2009" "Version 0.1" "BrainCognize" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BMainWindow.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBMainWindow\fP"
.br
.RI "\fIThis class contains the main window and the layout of the widgets within the window. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BrainCognize from the source code.
