.TH "BMainWindow" 3 "21 Apr 2009" "Version 0.1" "BrainCognize" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BMainWindow \- This class contains the main window and the layout of the widgets within the window.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <BMainWindow.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetupGUI\fP (QMainWindow *MainWindow)"
.br
.RI "\fISet up all widgets menus an buttons in the main window. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QAction * \fBm_actionLoad\fP"
.br
.ti -1c
.RI "QAction * \fBm_actionSave\fP"
.br
.ti -1c
.RI "QAction * \fBm_actionPreferences\fP"
.br
.ti -1c
.RI "QAction * \fBm_actionExit\fP"
.br
.ti -1c
.RI "QAction * \fBm_actionAbout_BrainCognize\fP"
.br
.ti -1c
.RI "QWidget * \fBm_centralwidget\fP"
.br
.ti -1c
.RI "QMenuBar * \fBm_menubar\fP"
.br
.ti -1c
.RI "QMenu * \fBm_menuFile\fP"
.br
.ti -1c
.RI "QMenu * \fBm_menuHelp\fP"
.br
.ti -1c
.RI "QStatusBar * \fBm_statusBar\fP"
.br
.ti -1c
.RI "QToolBar * \fBm_toolBar\fP"
.br
.ti -1c
.RI "\fBBQtGLWidget\fP * \fBm_glWidget\fP"
.br
.ti -1c
.RI "\fBBQtPipelineBrowser\fP * \fBm_pipelineBrowser\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class contains the main window and the layout of the widgets within the window. 
.PP
Definition at line 29 of file BMainWindow.h.
.SH "Member Function Documentation"
.PP 
.SS "void BMainWindow::setupGUI (QMainWindow * MainWindow)"
.PP
Set up all widgets menus an buttons in the main window. 
.PP
Definition at line 14 of file BMainWindow.cpp.
.PP
References m_actionAbout_BrainCognize, m_actionExit, m_actionLoad, m_actionPreferences, m_actionSave, m_centralwidget, m_glWidget, m_menubar, m_menuFile, m_menuHelp, m_pipelineBrowser, m_statusBar, and m_toolBar.
.PP
Referenced by main().
.SH "Member Data Documentation"
.PP 
.SS "QAction* \fBBMainWindow::m_actionLoad\fP\fC [private]\fP"
.PP
Definition at line 39 of file BMainWindow.h.
.PP
Referenced by setupGUI().
.SS "QAction* \fBBMainWindow::m_actionSave\fP\fC [private]\fP"
.PP
Definition at line 40 of file BMainWindow.h.
.PP
Referenced by setupGUI().
.SS "QAction* \fBBMainWindow::m_actionPreferences\fP\fC [private]\fP"
.PP
Definition at line 41 of file BMainWindow.h.
.PP
Referenced by setupGUI().
.SS "QAction* \fBBMainWindow::m_actionExit\fP\fC [private]\fP"
.PP
Definition at line 42 of file BMainWindow.h.
.PP
Referenced by setupGUI().
.SS "QAction* \fBBMainWindow::m_actionAbout_BrainCognize\fP\fC [private]\fP"
.PP
Definition at line 43 of file BMainWindow.h.
.PP
Referenced by setupGUI().
.SS "QWidget* \fBBMainWindow::m_centralwidget\fP\fC [private]\fP"
.PP
Definition at line 44 of file BMainWindow.h.
.PP
Referenced by setupGUI().
.SS "QMenuBar* \fBBMainWindow::m_menubar\fP\fC [private]\fP"
.PP
Definition at line 45 of file BMainWindow.h.
.PP
Referenced by setupGUI().
.SS "QMenu* \fBBMainWindow::m_menuFile\fP\fC [private]\fP"
.PP
Definition at line 46 of file BMainWindow.h.
.PP
Referenced by setupGUI().
.SS "QMenu* \fBBMainWindow::m_menuHelp\fP\fC [private]\fP"
.PP
Definition at line 47 of file BMainWindow.h.
.PP
Referenced by setupGUI().
.SS "QStatusBar* \fBBMainWindow::m_statusBar\fP\fC [private]\fP"
.PP
Definition at line 48 of file BMainWindow.h.
.PP
Referenced by setupGUI().
.SS "QToolBar* \fBBMainWindow::m_toolBar\fP\fC [private]\fP"
.PP
Definition at line 49 of file BMainWindow.h.
.PP
Referenced by setupGUI().
.SS "\fBBQtGLWidget\fP* \fBBMainWindow::m_glWidget\fP\fC [private]\fP"
.PP
Definition at line 51 of file BMainWindow.h.
.PP
Referenced by setupGUI().
.SS "\fBBQtPipelineBrowser\fP* \fBBMainWindow::m_pipelineBrowser\fP\fC [private]\fP"
.PP
Definition at line 52 of file BMainWindow.h.
.PP
Referenced by setupGUI().

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainCognize from the source code.
