.TH "BQtPipelineBrowser.h" 3 "21 Apr 2009" "Version 0.1" "BrainCognize" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BQtPipelineBrowser.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBQtPipelineBrowser\fP"
.br
.RI "\fIRepresents the browser showing the loaded data sets and applied filter/methods/algorithms/plugins. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BrainCognize from the source code.
