all:
	pdflatex openWalnutDesign
	pdflatex openWalnutDesign
	bibtex openWalnutDesign
	bibtex openWalnutDesign
	pdflatex openWalnutDesign
	pdflatex openWalnutDesign
	cp openWalnutDesign.pdf openWalnutDesignDocument.pdf
clean:
	rm openWalnutDesign.aux openWalnutDesign.log openWalnutDesign.out openWalnutDesign.toc openWalnutDesign.bbl openWalnutDesign.blg openWalnutDesign.pdf openWalnutDesignDocument.pdf
