execute_process(COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_BINARY_DIR}/bin/dataHandler)
execute_process(COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_BINARY_DIR}/bin/dataHandler/io)
execute_process(COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_BINARY_DIR}/bin/modules/marchingCubes)
FILE( GLOB_RECURSE ALL_FIXTURES1 ${OW_SOURCE_DIR}dataHandler/test/fixtures/* )
FILE( GLOB_RECURSE ALL_FIXTURES2 ${OW_SOURCE_DIR}/dataHandler/io/test/fixtures/* )
FILE( GLOB_RECURSE ALL_FIXTURES3 ${OW_SOURCE_DIR}/modules/marchingCubes/test/fixtures* )
FOREACH( fname ${ALL_FIXTURES1} )
  configure_file(  ${fname} ${CMAKE_BINARY_DIR}/bin/dataHandler COPYONLY)
ENDFOREACH( fname )
FOREACH( fname ${ALL_FIXTURES2} )
  configure_file(  ${fname} ${CMAKE_BINARY_DIR}/bin/dataHandler/io COPYONLY)
ENDFOREACH( fname )
FOREACH( fname ${ALL_FIXTURES3} )
  configure_file(  ${fname} ${CMAKE_BINARY_DIR}/bin/modules/marchingCubes COPYONLY)
ENDFOREACH( fname )
