#!/bin/bash

#---------------------------------------------------------------------------
#
# Project: OpenWalnut ( http://www.openwalnut.org )
#
# Copyright 2009 OpenWalnut Community, BSV@Uni-Leipzig and CNCF@MPI-CBS
# For more information see http://www.openwalnut.org/copying
#
# This file is part of OpenWalnut.
#
# OpenWalnut is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# OpenWalnut is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with OpenWalnut. If not, see <http://www.gnu.org/licenses/>.
#
#---------------------------------------------------------------------------

#############################################################################################################
# Internal Variables
#############################################################################################################

# what to build
ARCHITECTURES="amd64 i386"
DISTRIBUTIONS="sid wheezy squeeze lucid maverick natty"
PACKAGES="deb"

# Where to put logs from this script not distri/arch or pack specific.
MAINLOGFILE="$0.log"

#############################################################################################################
# Functions
#############################################################################################################

#########################################################################################################
# Clean up previous mess
Purge()
{
    # we need root since the build-user in the chroot is root and created some
    # files
    rm -f $0-*.log
    rm -f $MAINLOGFILE
    sudo ./owpack purge || exit $?
}

#########################################################################################################
# Build for different target systems
BuildAll()
{
    echo "LOG created by $0 on `date`" > $MAINLOGFILE

    # init
    ./owpack init | tee -a $MAINLOGFILE || exit $?

    for distri in $DISTRIBUTIONS
    do
        for arch in $ARCHITECTURES
        do
            for pack in $PACKAGES
            do
                LOGFILE=$0-$pack-$distri-$arch.log
                echo "LOG created by $0 on `date`" > $LOGFILE

                echo "* Building $pack for \"$distri-$arch\". Log: $LOGFILE" | tee -a $MAINLOGFILE

                # check for chroot existence
                sudo ./owbuildchroot $arch $distri check >> $MAINLOGFILE
                if [ $? -ne 0 ]; then
                    echo " * Error. Build chroot not found." | tee -a $MAINLOGFILE
                    continue
                fi

                # create a log
                sudo ./owbuildchroot $arch $distri run /build/owpack $pack $distri-$arch /build >> $LOGFILE

                # for later error reporting
                if [ $? -ne 0 ]; then
                    echo " * Error while building for \"$distri\", $arch. Check \"$LOGFILE\" for details" | tee -a $MAINLOGFILE
                    continue
                fi
            done
        done
    done
}

#########################################################################################################
# Main

# Handle user command
case "$1" in
    purge)
        Purge || exit $?
        ;;
    build)
        Purge || exit $?
        BuildAll || exit $?
        ;;
    *)
        echo "Usage: $0 {purge|build}"
        echo "  COMMANDS:"
        echo "    purge: Purges logs and calls owpack purge."
        echo "    build: Build all."
        echo ""
        exit 2
        ;;
esac
