#!/bin/bash
#otool -l bin/walnut |grep osg
#otool -l bin/walnut |grep OpenThreads

INPARAM="$1"
MAKESYSTEM="-s"
HELP="-h"
if [ "$INPARAM" = "$HELP" ]  
then 
    echo "Usage: "
    echo " -h Prints this help"
    echo " -s fixes also system libs"
    exit
fi

###### OpenWalnut Libs #####

for i in bin/*; do \
    if [ -f $i ]
    then
        install_name_tool \
            -change libosgDB.55.dylib /opt/local/lib/libosgDB.55.dylib \
            -change libosgText.55.dylib /opt/local/lib/libosgText.55.dylib \
            -change libosgGA.55.dylib /opt/local/lib/libosgGA.55.dylib \
            -change libosgUtil.55.dylib /opt/local/lib/libosgUtil.55.dylib \
            -change libosgViewer.55.dylib /opt/local/lib/libosgViewer.55.dylib \
            -change libOpenThreads.11.dylib /opt/local/lib/libOpenThreads.11.dylib \
            -change libosg.55.dylib /opt/local/lib/libosg.55.dylib \
            $i;
    fi
done

for i in lib/*; do \
install_name_tool \
 -change libosgDB.55.dylib /opt/local/lib/libosgDB.55.dylib \
 -change libosgText.55.dylib /opt/local/lib/libosgText.55.dylib \
 -change libosgGA.55.dylib /opt/local/lib/libosgGA.55.dylib \
 -change libosgUtil.55.dylib /opt/local/lib/libosgUtil.55.dylib \
 -change libosgViewer.55.dylib /opt/local/lib/libosgViewer.55.dylib \
 -change libOpenThreads.11.dylib /opt/local/lib/libOpenThreads.11.dylib \
 -change libosg.55.dylib /opt/local/lib/libosg.55.dylib \
 $i; done


###### OSG Libs ######

if [ "$INPARAM" = "$MAKESYSTEM" ]  
then 
     echo "help"
     install_name_tool \
         -change libosg.55.dylib /opt/local/lib/libosg.55.dylib \
         -change libOpenThreads.11.dylib /opt/local/lib/libOpenThreads.11.dylib \
         /opt/local/lib/libosgDB.55.dylib
     
     install_name_tool \
         -change libOpenThreads.11.dylib /opt/local/lib/libOpenThreads.11.dylib \
         /opt/local/lib/libosg.55.dylib
     
     install_name_tool \
         -change libOpenThreads.11.dylib /opt/local/lib/libOpenThreads.11.dylib \
         -change libosg.55.dylib /opt/local/lib/libosg.55.dylib \
         -change libosgDB.55.dylib /opt/local/lib/libosgDB.55.dylib \
         /opt/local/lib/libosgText.55.dylib
     
     install_name_tool \
         -change libOpenThreads.11.dylib /opt/local/lib/libOpenThreads.11.dylib \
         -change libosgDB.55.dylib /opt/local/lib/libosgDB.55.dylib \
         -change libosgUtil.55.dylib /opt/local/lib/libosgUtil.55.dylib \
         -change libosg.55.dylib /opt/local/lib/libosg.55.dylib \
         /opt/local/lib/libosgGA.55.dylib
     
     install_name_tool \
         -change libOpenThreads.11.dylib /opt/local/lib/libOpenThreads.11.dylib \
         -change libosgUtil.55.dylib /opt/local/lib/libosgUtil.55.dylib \
         -change libosg.55.dylib /opt/local/lib/libosg.55.dylib \
         /opt/local/lib/libosgUtil.55.dylib
     
     install_name_tool \
         -change libosgDB.55.dylib /opt/local/lib/libosgDB.55.dylib \
         -change libosgText.55.dylib /opt/local/lib/libosgText.55.dylib \
         -change libOpenThreads.11.dylib /opt/local/lib/libOpenThreads.11.dylib \
         -change libosgUtil.55.dylib /opt/local/lib/libosgUtil.55.dylib \
         -change libosg.55.dylib /opt/local/lib/libosg.55.dylib \
         -change libosgGA.55.dylib /opt/local/lib/libosgGA.55.dylib \
         /opt/local/lib/libosgViewer.55.dylib
fi