#!/bin/bash
#otool -l bin/walnut |grep osg
#otool -l bin/walnut |grep OpenThreads

###### OpenWalnut Libs #####

install_name_tool \
 -change libosgDB.55.dylib /opt/local/lib/libosgDB.55.dylib \
 -change libosgText.55.dylib /opt/local/lib/libosgText.55.dylib \
 -change libosgGA.55.dylib /opt/local/lib/libosgGA.55.dylib \
 -change libosgUtil.55.dylib /opt/local/lib/libosgUtil.55.dylib \
 -change libosgViewer.55.dylib /opt/local/lib/libosgViewer.55.dylib \
 -change libOpenThreads.11.dylib /opt/local/lib/libOpenThreads.11.dylib \
 -change libosg.55.dylib /opt/local/lib/libosg.55.dylib \
 bin/walnut

for i in lib/*; do \
install_name_tool \
 -change libosgDB.55.dylib /opt/local/lib/libosgDB.55.dylib \
 -change libosgText.55.dylib /opt/local/lib/libosgText.55.dylib \
 -change libosgGA.55.dylib /opt/local/lib/libosgGA.55.dylib \
 -change libosgUtil.55.dylib /opt/local/lib/libosgUtil.55.dylib \
 -change libosgViewer.55.dylib /opt/local/lib/libosgViewer.55.dylib \
 -change libOpenThreads.11.dylib /opt/local/lib/libOpenThreads.11.dylib \
 -change libosg.55.dylib /opt/local/lib/libosg.55.dylib \
 $i; done

###### OSG Libs ######

install_name_tool \
 -change libosg.55.dylib /opt/local/lib/libosg.55.dylib \
 -change libOpenThreads.11.dylib /opt/local/lib/libOpenThreads.11.dylib \
 /opt/local/lib/libosgDB.55.dylib

install_name_tool \
 -change libOpenThreads.11.dylib /opt/local/lib/libOpenThreads.11.dylib \
 /opt/local/lib/libosg.55.dylib

install_name_tool \
 -change libOpenThreads.11.dylib /opt/local/lib/libOpenThreads.11.dylib \
 -change libosg.55.dylib /opt/local/lib/libosg.55.dylib \
 -change libosgDB.55.dylib /opt/local/lib/libosgDB.55.dylib \
 /opt/local/lib/libosgText.55.dylib

install_name_tool \
 -change libOpenThreads.11.dylib /opt/local/lib/libOpenThreads.11.dylib \
 -change libosgDB.55.dylib /opt/local/lib/libosgDB.55.dylib \
 -change libosgUtil.55.dylib /opt/local/lib/libosgUtil.55.dylib \
 -change libosg.55.dylib /opt/local/lib/libosg.55.dylib \
 /opt/local/lib/libosgGA.55.dylib

install_name_tool \
 -change libOpenThreads.11.dylib /opt/local/lib/libOpenThreads.11.dylib \
 -change libosgUtil.55.dylib /opt/local/lib/libosgUtil.55.dylib \
 -change libosg.55.dylib /opt/local/lib/libosg.55.dylib \
 /opt/local/lib/libosgUtil.55.dylib

install_name_tool \
 -change libosgDB.55.dylib /opt/local/lib/libosgDB.55.dylib \
 -change libosgText.55.dylib /opt/local/lib/libosgText.55.dylib \
 -change libOpenThreads.11.dylib /opt/local/lib/libOpenThreads.11.dylib \
 -change libosgUtil.55.dylib /opt/local/lib/libosgUtil.55.dylib \
 -change libosg.55.dylib /opt/local/lib/libosg.55.dylib \
 -change libosgGA.55.dylib /opt/local/lib/libosgGA.55.dylib \
 /opt/local/lib/libosgViewer.55.dylib